[versions]
spring-boot = "2.5.6"
nokee = "0.5.0-74867535"

[plugins]
nokee-jni = { id = "dev.nokee.jni-library", version.ref = "nokee" }
nokee-c-language = { id = "dev.nokee.c-language", version.ref = "nokee" }
nokee-c-library = { id = "dev.nokee.c-library", version.ref = "nokee" }

spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }

[libraries]
spring-boot-bom = { module = "org.springframework.boot:spring-boot-dependencies", version.ref = "spring-boot" }
